#!/bin/bash

# Check if correct number of arguments is provided
if [ "$#" -ne 2 ]; then
    echo "How to use the plugin: $0 <Enter the name of node or pod> <Enter the name of namespace>"
    exit 1
fi

# Specify the variables
RESOURCE_TYPE=$1  # node, pod
NAMESPACE=$2    # namespace

# Retrieve resource usage statistics from Kubernetes
kubectl top $RESOURCE_TYPE -n $NAMESPACE --no-headers=true | while read -r line
do
    # Extract Name, CPU, and Memory
    NAME=$(echo "$line" | awk '{print $1}')
    CPU=$(echo "$line" | awk '{print $2}')
    MEMORY=$(echo "$line" | awk '{print $3}')

    # Output the statistics to the console
    echo "$RESOURCE_TYPE, $NAMESPACE, $NAME, $CPU, $MEMORY"
done
